{% set version = "1.12.0" %}

# Note: This recipe is specifically designed to work well with the autotick bot.
# Also refer to https://github.com/conda-forge/rust-feedstock/blob/main/recipe/meta.yaml.
package:
  name: {{ polars_variant }}
  version: {{ version }}

source:
  - url: https://github.com/pola-rs/polars/archive/5210697fdeb006fe99264c56cbe6b9b504072383.tar.gz
    sha256: c48b9390bedabae3432edfa0f202b4d1370726beb72d1bd957e732645625994c

build:
  number: 1

requirements:
  build:
    - python                              # [build_platform != target_platform]
    # there is no cross-python for linux-64 -> win-64
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not target_platform == "win-64"]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.3.2,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}               # [win]
    # clang_win-64 already adds all required run_exports for the windows build
    - {{ stdlib("c") }}  # [not (build_platform == "linux-64" and target_platform == "win-64")]
    - {{ compiler('rust') }}
    - posix                               # [build_platform == "win-64"]
    - cmake
    - make                                # [unix]
    - cargo-feature                       # [build_platform != target_platform and target_platform == "win-64"]
    - cargo-bundle-licenses
    - curl
  host:
    - python
    - pip
    - maturin >=1.3.2,<2
  run:
    - python
    - numpy >=1.16.0
    - backports.zoneinfo                   # [py<39]
    - typing_extensions >=4.0.0            # [py<311]
    - packaging                            # [py>=310]

test:
  imports:
    - polars
  commands:
    - pip check
    - python -c "from polars import DataFrame"
  requires:
    - pip

about:
  home: https://github.com/pola-rs/polars
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  doc_url: https://pola-rs.github.io/polars-book/user-guide/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - '0xbe7a'
